mongodb:
  image: dockerfile/mongodb:latest
  restart: always
sourcetor:
   image: acaceres2176/sourcetor
   restart: always
splash:
  image: scrapinghub/splash:latest
  volumes: 
    - "./torstuff/proxy-profiles:/etc/splash/proxy-profiles"
  links:
    - sourcetor
  restart: always
sourcepin:
#  for developers- to build with your code changes, replace the image: block with the build: block below 
#  then type sudo fig build followed by sudo fig up, your changes should now be in SourcePin
  build: .
#  image: acaceres2176/sourcepin
  volumes: 
    - /data/db:/data/db
  ports:
    - "80:80"
    - "6800:6800"
  links:
    - mongodb
    - splash
    - sourcetor
  restart: always
    